'''Export debate results to Markdown, JSON, or plain text.'''

import json
from datetime import datetime


def to_markdown(debate: dict) -> str:
    lines = [
        f"# Debate: {debate.get('topic', 'N/A')}",
        f"",
        f"**Format:** {debate.get('format', 'Free Form')} | **Rounds:** {debate.get('rounds', 3)} | **Status:** {debate.get('status', 'N/A')}",
        f"**Started:** {debate.get('started_at', 'N/A')}",
        f"",
        f"---",
        f"",
        f"## Participants",
        f"",
    ]

    for agent in debate.get('agents', []):
        lines.append(f"- **{agent}**")

    lines.extend(["", "---", "", "## Debate Transcript", ""])

    for entry in debate.get('history', []):
        lines.append(f"### Round {entry.get('round', '?')} — {entry.get('agent', 'Unknown')}")
        lines.append(f"")
        lines.append(entry.get('content', ''))
        lines.append(f"")
        lines.append(f"*({entry.get('latency_ms', 0):.0f}ms)*")
        lines.append("")

    judgment = debate.get('judgment', {})
    if judgment:
        lines.extend([
            "---",
            "",
            "## Judge's Verdict",
            "",
            f"**Winner:** {judgment.get('winner', 'N/A')}",
            "",
            f"**Reasoning:** {judgment.get('reasoning', 'N/A')}",
            "",
        ])

        scores = judgment.get('scores', {})
        if scores:
            lines.append("### Scores")
            lines.append("")
            for agent, score in scores.items():
                lines.append(f"- **{agent}**: {score}/10")
            lines.append("")

        key_args = judgment.get('key_arguments', [])
        if key_args:
            lines.append("### Key Arguments")
            lines.append("")
            for arg in key_args:
                lines.append(f"- {arg}")
            lines.append("")

        weaknesses = judgment.get('weaknesses', [])
        if weaknesses:
            lines.append("### Weaknesses Identified")
            lines.append("")
            for w in weaknesses:
                lines.append(f"- {w}")
            lines.append("")

    lines.extend([
        "---",
        f"*Generated by Hivemind — AI Debate Platform — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*"
    ])

    return "\n".join(lines)


def to_json(debate: dict) -> str:
    return json.dumps(debate, indent=2, default=str)


def to_plain(debate: dict) -> str:
    lines = [f"DEBATE: {debate.get('topic', 'N/A')}", "=" * 60, ""]
    for entry in debate.get('history', []):
        lines.append(f"[Round {entry.get('round', '?')}] {entry.get('agent', '?')}:")
        lines.append(entry.get('content', ''))
        lines.append("")
    judgment = debate.get('judgment', {})
    if judgment:
        lines.append(f"WINNER: {judgment.get('winner', 'N/A')}")
        lines.append(f"REASON: {judgment.get('reasoning', 'N/A')}")
    return "\n".join(lines)
